#!/usr/bin/with-contenv ash

echo "Starting Deluge Bittorrent WebUI."
export PYTHON_EGG_CACHE="/config/plugins/.python-eggs"
exec s6-setuidgid deluge deluge-web -c /config -l /config/deluge-web.log -L warning
