#!/bin/bash

# Tag releases as latest and betas as beta
if [[ "$DOCKER_TAG" =~ ^[0-9.]+$ ]]; then
  echo Tag $DOCKER_TAG is a release, tagging as latest
  docker tag $IMAGE_NAME $DOCKER_REPO:latest
  docker push $DOCKER_REPO:latest
elif [[ "$DOCKER_TAG" =~ ^[0-9.]+-beta.*$ ]]; then
  echo Tag $DOCKER_TAG is a beta, tagging as beta
  docker tag $IMAGE_NAME $DOCKER_REPO:beta
  docker push $DOCKER_REPO:beta
fi
