#!/bin/bash

# Tag releases as latest and others based on DockeHub tag
if [[ "$DOCKER_TAG" =~ ^[0-9.]+$ ]]; then
  echo Tag $DOCKER_TAG is a release, tagging as latest
  docker tag $IMAGE_NAME $DOCKER_REPO:latest
  docker push $DOCKER_REPO:latest
else
  VERSION=$DOCKER_TAG-`date -u +"%Y%m%d%H%M%S"`-`git rev-parse --short HEAD`
  echo Tag $DOCKER_TAG is not a release, tagging as $VERSION
  docker tag $IMAGE_NAME $DOCKER_REPO:$VERSION
  docker push $DOCKER_REPO:$VERSION
fi
