#!/usr/bin/with-contenv ash

# If the first run completed successfully, we are done
if [ -e /.firstRunComplete ]; then
  exit 0
fi

echo "Running Deluge first run setup..."

# Add user and group
addgroup -g ${DELUGE_GID:-2000} -S deluge
adduser -h /config -s /sbin/nologin -G deluge -S -D -H -u ${DELUGE_UID:-2000} -k /dev/null deluge

# Set some sane defaults if there's no config file yet
if [ ! -f /config/core.conf ]; then
  cp /deluge-core.conf /config/core.conf
  # TODO Add default config for deluge-web
fi

# Update ownership of dirs we need to write to
chown -R deluge:deluge /config /data

touch /.firstRunComplete
echo "Deluge first run setup complete"
